//! HKDF-SHA256 helpers (RFC 5869) used by PROTOCOL.md §3.2 and
//! EVE_API_CONTRACT.md §2.2.
//!
//! We wrap the `hkdf` crate with fixed-output-length expand helpers so call
//! sites cannot accidentally produce the wrong length.

use hkdf::Hkdf;
use sha2::Sha256;

/// HKDF-Extract(salt, ikm) -> PRK.
pub fn extract(salt: &[u8], ikm: &[u8]) -> [u8; 32] {
    let (prk, _) = Hkdf::<Sha256>::extract(Some(salt), ikm);
    prk.into()
}

/// HKDF-Expand(PRK, info, 32).
pub fn expand_32(prk: &[u8; 32], info: &[u8]) -> [u8; 32] {
    let hk = Hkdf::<Sha256>::from_prk(prk).expect("32-byte PRK is valid");
    let mut out = [0u8; 32];
    hk.expand(info, &mut out).expect("L=32 is a valid HKDF length");
    out
}

/// HKDF-Expand(PRK, info, 12) — nonce salts.
pub fn expand_12(prk: &[u8; 32], info: &[u8]) -> [u8; 12] {
    let hk = Hkdf::<Sha256>::from_prk(prk).expect("32-byte PRK is valid");
    let mut out = [0u8; 12];
    hk.expand(info, &mut out).expect("L=12 is a valid HKDF length");
    out
}

/// One-shot HKDF-SHA256: extract with `salt`, expand with `info` into
/// `out`. This is the shape named in EVE_API_CONTRACT.md §2.2.
pub fn hkdf_sha256(ikm: &[u8], salt: &[u8], info: &[u8], out: &mut [u8]) {
    let hk = Hkdf::<Sha256>::new(Some(salt), ikm);
    hk.expand(info, out).expect("requested HKDF length too large");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// RFC 5869 Appendix A, Test Case 1 (SHA-256).
    #[test]
    fn rfc5869_case_1() {
        let ikm = [0x0bu8; 22];
        let salt = hex::decode("000102030405060708090a0b0c").unwrap();
        let info = hex::decode("f0f1f2f3f4f5f6f7f8f9").unwrap();
        let expected_prk =
            hex::decode("077709362c2e32df0ddc3f0dc47bba6390b6c73bb50f9c3122ec844ad7c2b3e5")
                .unwrap();
        let expected_okm_prefix =
            hex::decode("3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf")
                .unwrap();

        let prk = extract(&salt, &ikm);
        assert_eq!(prk.as_slice(), expected_prk.as_slice());

        let mut okm = [0u8; 42];
        let hk = Hkdf::<Sha256>::from_prk(&prk).unwrap();
        hk.expand(&info, &mut okm).unwrap();
        assert_eq!(&okm[..32], expected_okm_prefix.as_slice());
    }

    /// RFC 5869 Appendix A, Test Case 2 (SHA-256, longer inputs).
    #[test]
    fn rfc5869_case_2() {
        let ikm = hex::decode(
            "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f\
             202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f\
             404142434445464748494a4b4c4d4e4f",
        )
        .unwrap();
        let salt = hex::decode(
            "606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f\
             808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f\
             a0a1a2a3a4a5a6a7a8a9aaabacadaeaf",
        )
        .unwrap();
        let info = hex::decode(
            "b0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecf\
             d0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7e8e9eaebecedeeef\
             f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff",
        )
        .unwrap();
        let expected_okm_prefix = hex::decode(
            "b11e398dc80327a1c8e7f78c596a49344f012eda2d4efad8a050cc4c19afa97c\
             59045a99cac7827271cb41c65e590e09da3275600c2f09b8367793a9aca3db71\
             cc30c58179ec3e87c14c01d5c1f3434f1d87",
        )
        .unwrap();

        let mut okm = [0u8; 82];
        hkdf_sha256(&ikm, &salt, &info, &mut okm);
        assert_eq!(okm.as_slice(), expected_okm_prefix.as_slice());
    }

    /// Cross-check against an independent HKDF-SHA256 computation in Python
    /// (hashlib/hmac, RFC 5869 construction), for the exact contract §2.2
    /// derivation:
    ///   key = HKDF-SHA256(ikm=session_seed, salt="bnqo-v1", info=<dir>, L=32)
    ///
    /// session_seed = hex 000102...1f, generated by docs' Python equivalent:
    ///   python3 - <<'EOF'
    ///   import hashlib, hmac as hmac_mod
    ///   seed = bytes(range(32))
    ///   prk = hmac_mod.new(b"bnqo-v1", seed, hashlib.sha256).digest()
    ///   def expand(info):
    ///       return hmac_mod.new(prk, info + b"\x01", hashlib.sha256).digest()
    ///   print(expand(b"a_to_b").hex())
    ///   print(expand(b"b_to_a").hex())
    ///   EOF
    #[test]
    fn contract_directional_keys_match_python() {
        let seed: [u8; 32] = core::array::from_fn(|i| i as u8);
        let prk = extract(b"bnqo-v1", &seed);
        assert_eq!(
            hex::encode(expand_32(&prk, b"a_to_b")),
            "772119c3a030946c598e138c47febc27dde679349133783ace55e978e4baa57e"
        );
        assert_eq!(
            hex::encode(expand_32(&prk, b"b_to_a")),
            "1d7b7345a44d4326c130f4445f6942abba04b76a16f748743857b54ae68c3419"
        );
        assert_eq!(
            hex::encode(expand_12(&prk, b"a_to_b_salt")),
            "f1475bf107671c535a813c7e"
        );
        assert_eq!(
            hex::encode(expand_12(&prk, b"b_to_a_salt")),
            "7520c7d4ba8bd05348bf5a3f"
        );

        // PROTOCOL.md §3.2 derivation: salt = session_id BE64.
        let prk2 = extract(&42u64.to_be_bytes(), &seed);
        assert_eq!(
            hex::encode(expand_32(&prk2, b"bnqo-udp-v1|a2b|key")),
            "94cacecc6262dd60a970a9ba6caf3925d379656b1cbbbcbf84d0a54b20eabe9e"
        );
        assert_eq!(
            hex::encode(expand_12(&prk2, b"bnqo-udp-v1|a2b|salt")),
            "2af6cecf5149a49808bdbafb"
        );
    }
}
